print("ax^2 + bx + c = 0")
a=int(input("Enter value of a: "))
b=int(input("Enter value of b: "))
c=int(input("Enter value of c: "))
root1=(-b+((b**2)-(4*a*c))**(1/2))/(2*a)
root2=(-b-((b**2)-(4*a*c))**(1/2))/(2*a)
print("Roots are:",root1,"and",root2)